### ISSUE TITLE
ValueError: DataFrame constructor not properly called!

### ISSUE THREAD

**Issue by ziayounasch** [sunnysavita10/genai#1]
Hi
I am facing an error when I upload PDF to create MCQs. The error is as under:

`Traceback (most recent call last):
  File "C:\Users\Dell13\Desktop\genai-main\mcqgenrator\utils.py", line 29, in get_table_data
    quiz_dict=json.loads(quiz_str)
              ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dell13\AppData\Local\Programs\Python\Python311\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dell13\AppData\Local\Programs\Python\Python311\Lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dell13\AppData\Local\Programs\Python\Python311\Lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2024-05-09 14:43:20.407 Uncaught app exception
Traceback (most recent call last):
  File "C:\Users\Dell13\Desktop\genai-main\genai\Lib\site-packages\streamlit\runtime\scriptrunner\script_runner.py", line 600, in _run_script
    exec(code, module.__dict__)
  File "C:\Users\Dell13\Desktop\genai-main\StreamlitApp.py", line 71, in <module>
    df=pd.DataFrame(table_data)
       ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dell13\Desktop\genai-main\genai\Lib\site-packages\pandas\core\frame.py", line 886, in __init__
    raise ValueError("DataFrame constructor not properly called!")
ValueError: DataFrame constructor not properly called!
`

**Comment by ziayounasch** [comment]
Can you please resolve it?
